boxes = [
  { :name => "router-1", :ip => "192.168.57.11", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048,
    :networks => ["10.47.77.1", "172.31.90.1", "10.31.225.1", "10.0.103.1"] },
  { :name => "router-2", :ip => "192.168.57.12", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048,
    :networks => ["10.0.78.1", "10.0.103.2"] },
  { :name => "router-3", :ip => "192.168.57.13", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048,
    :networks => ["172.31.90.2", "172.24.71.1"] },
  { :name => "router-4", :ip => "192.168.57.14", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048,
    :networks => ["10.0.78.2", "10.47.77.2"] },
  { :name => "router-5", :ip => "192.168.57.15", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048,
    :networks => ["10.31.225.2", "172.24.71.2"] },
  { :name => "docker-1", :ip => "192.168.57.21", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
  { :name => "docker-2", :ip => "192.168.57.22", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
  { :name => "pc-3", :ip => "192.168.57.23", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
  { :name => "server-4", :ip => "192.168.57.24", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
]

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
end
