boxes = [
  { :name => "router-1", :ip => "192.168.57.11", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 1024,
    :networks => ["10.0.47.1", "192.168.245.1", "10.0.31.1", "10.103.31.1"] },
  { :name => "router-2", :ip => "192.168.57.12", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 1024,
    :networks => ["10.78.182.1", "10.103.31.2"] },
  { :name => "router-3", :ip => "192.168.57.13", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 1024,
    :networks => ["192.168.245.2", "192.168.132.1"] },
  { :name => "router-4", :ip => "192.168.57.14", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 1024,
    :networks => ["10.78.182.2", "10.0.47.2"] },
  { :name => "router-5", :ip => "192.168.57.15", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 1024,
    :networks => ["10.0.31.2", "192.168.132.2"] },
  { :name => "docker-1", :ip => "192.168.57.16", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
  { :name => "docker-2", :ip => "192.168.57.17", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
  { :name => "pc-3", :ip => "192.168.57.18", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 1024 },
  { :name => "server-4", :ip => "192.168.57.19", :box => "generic/ubuntu2204",
    :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 1024 },
]

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
end
