# ad/Scenario3/providers/vmware/Vagrantfile
#
# This file defines ONLY the lab VM data array.
# The Vagrant.configure block is supplied by the GOAD framework template at:
#   template/provider/vmware/Vagrantfile
#
# PROVISIONING (jumpbox) VM is also added by the template — do not add it here.
# The template uses :os to distinguish WinRM (windows) from SSH (linux) VMs.

boxes = [
  { :name => "router-1",  :ip => "192.168.57.11", :box => "generic/ubuntu2204", :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
  { :name => "router-2",  :ip => "192.168.57.12", :box => "generic/ubuntu2204", :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
  { :name => "router-3",  :ip => "192.168.57.13", :box => "generic/ubuntu2204", :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
  { :name => "router-4",  :ip => "192.168.57.14", :box => "generic/ubuntu2204", :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
  { :name => "router-5",  :ip => "192.168.57.15", :box => "generic/ubuntu2204", :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
  { :name => "pc-1",      :ip => "192.168.57.21", :box => "generic/ubuntu2204", :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
  { :name => "pc-3",      :ip => "192.168.57.23", :box => "generic/ubuntu2204", :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
  { :name => "pc-4",      :ip => "192.168.57.24", :box => "generic/ubuntu2204", :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
  { :name => "pc-5",      :ip => "192.168.57.25", :box => "generic/ubuntu2204", :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
  { :name => "pc-8",      :ip => "192.168.57.28", :box => "generic/ubuntu2204", :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
  { :name => "docker-11", :ip => "192.168.57.31", :box => "generic/ubuntu2204", :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
  { :name => "docker-12", :ip => "192.168.57.32", :box => "generic/ubuntu2204", :box_version => "4.3.12", :os => "linux", :cpus => 1, :mem => 2048 },
]
