# ad/Scenario3/providers/virtualbox/Vagrantfile
#
# boxes is defined at the top-level Ruby scope (outside Vagrant.configure)
# so it is accessible regardless of how the GOAD framework loads this file.
#
# PROVISIONING keeps its Vagrant-generated key so local_jumpbox.py can find it.
# All lab VMs use ssh.insert_key = false to keep the Vagrant insecure key,
# which the jumpbox installs at ~/.vagrant.d/insecure_private_key.

boxes = [
  { name: "PROVISIONING", ip: "192.168.57.3",  memory: 2048, cpus: 2, os: "linux", jumpbox: true  },
  { name: "router-1",     ip: "192.168.57.11", memory: 2048, cpus: 1, os: "linux", jumpbox: false },
  { name: "router-2",     ip: "192.168.57.12", memory: 2048, cpus: 1, os: "linux", jumpbox: false },
  { name: "router-3",     ip: "192.168.57.13", memory: 2048, cpus: 1, os: "linux", jumpbox: false },
  { name: "router-4",     ip: "192.168.57.14", memory: 2048, cpus: 1, os: "linux", jumpbox: false },
  { name: "router-5",     ip: "192.168.57.15", memory: 2048, cpus: 1, os: "linux", jumpbox: false },
  { name: "pc-1",         ip: "192.168.57.21", memory: 2048, cpus: 1, os: "linux", jumpbox: false },
  { name: "pc-3",         ip: "192.168.57.23", memory: 2048, cpus: 1, os: "linux", jumpbox: false },
  { name: "pc-4",         ip: "192.168.57.24", memory: 2048, cpus: 1, os: "linux", jumpbox: false },
  { name: "pc-5",         ip: "192.168.57.25", memory: 2048, cpus: 1, os: "linux", jumpbox: false },
  { name: "pc-8",         ip: "192.168.57.28", memory: 2048, cpus: 1, os: "linux", jumpbox: false },
  { name: "docker-11",    ip: "192.168.57.31", memory: 2048, cpus: 1, os: "linux", jumpbox: false },
  { name: "docker-12",    ip: "192.168.57.32", memory: 2048, cpus: 1, os: "linux", jumpbox: false },
]

Vagrant.configure("2") do |config|
  boxes.each do |box|
    config.vm.define box[:name] do |vm_config|
      vm_config.vm.box         = "generic/ubuntu2204"
      vm_config.vm.box_version = "4.3.12"
      vm_config.vm.hostname    = box[:name]
      vm_config.vm.network "private_network", ip: box[:ip]

      unless box[:jumpbox]
        vm_config.ssh.insert_key = false
      end

      vm_config.vm.provider "virtualbox" do |vb|
        vb.memory = box[:memory]
        vb.cpus   = box[:cpus]
      end
    end
  end
end
