---
- import_playbook: data.yml
  vars:
    data_path: "../ad/Scenario3/data"
  tags: 'data'

- name: "Configure HITL participant network interface"
  hosts: hitl_router
  become: true
  roles:
    - { role: 'network/hitl_interface', tags: 'hitl_interface' }
  vars:
    hostname: "{{lab.hosts[dict_key].hostname}}"
    hitl_interface_name: "{{lab.hosts[dict_key].hitl_interface.slug}}"
    hitl_ip4: "{{lab.hosts[dict_key].hitl_interface.ip4}}"
    hitl_rj45_ip4: "{{lab.hosts[dict_key].hitl_interface.rj45_ip4}}"
    hitl_network: "{{lab.hosts[dict_key].hitl_interface.network}}"
    hitl_attachment: "{{lab.hosts[dict_key].hitl_interface.attachment}}"
    router_lan_ip4: "{{lab.hosts[dict_key].ip4}}"

- name: "Add route for HITL participant network"
  hosts: hitl_router
  become: true
  roles:
    - { role: 'network/hitl_forwarding', tags: 'hitl_forwarding' }
  vars:
    hitl_network: "{{lab.hosts[dict_key].hitl_interface.network}}"
    hitl_gateway: "{{lab.hosts[dict_key].hitl_interface.rj45_ip4 | ansible.utils.ipaddr('address')}}"
